### ISSUE TITLE
Duplicated tensorboard output

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#32]
I'm seeing duplicate Tensorboard runs for any guild run that happened as part of a batch. What seems to be happening is that guild is creating symlinks to each individual run folder, as well as a symlink to the parent (batch) folder, which in turn has symlinks to each of the individual runs. Given that the direct links to individual runs have a better name (it includes the run label), perhaps the thing to do is to stop adding symlinks to batch folders for Tensorboard? 

Happy to provide more details of my setup if this is hard to reproduce.

**Comment by gar1t** [comment]
Thank you, yes you're right! This is fixed and available to test in the `0.6.5.dev6` pre-release. You can install that version by running `pip install guildai --upgrade --pre`. Otherwise `0.6.5` will go out later this week.

**Comment by AndrewPaulChester** [comment]
This seems to still be happening in 0.6.5, including for runs performed after I upgraded.

**Comment by gar1t** [comment]
In my tests on `0.6.5`, I'm only seeing the non-batch runs. Just to confirm we're seeing the same thing (at least as a control), could you clone [Guild examples](https://github.com/guildai/examples) and run this?

    $ cd examples/noisy
    $ guild run noisy.py x=[1,2,3] -y
    $ guild tensorboard

On my environment, I'm seeing only the three noisy.py runs - not the batch run. So the values reported in TensorBoard are not duplicated.

For this test, there is the matter of ensuring that you're not looking at any other runs by accident. You can filter using `guild tensorboard -o noisy.py` but that could spoil the test. The safest way would be to either run this test in a new virtual env or to temporarily move existing runs into an archive before running the code above. I've provided steps for either approach below.

Option 1: Create a virtual env:

    $ virtualenv /tmp/guild-issue-32
    $ source /tmp/guild-issue-32/bin/activate
    $ pip install guildai
    <run test steps above>
    $ deactivate && rm -rf /tmp/guild-issue-32

Option 2: Temporarily move existing runs:

    $ guild export --move guild-issue-32-archive
    <run test steps above>
    $ guild import --move guild-issue-32-archive
    $ rmdir guild-issue-32-archive

**Comment by gar1t** [comment]
I created a project to help recreate the current behavior:

https://github.com/guildai/issue-resolution/tree/master/32-duplicated-tensorboard-output

I'm not able to see batch runs anymore in TensorBoard as of 0.6.5. If you're seeing something different, please update here so we can investigate!

**Comment by AndrewPaulChester** [comment]
I see what's going on here - I'm only seeing duplicated runs when i go to TensorBoard through guild view, not directly. So the issues script provided works as expected, but if you change the last line to guild view instead then click through to TensorBoard you still see the duplicates. Not sure how you want to handle this, for my purposes at least I'm happy with using guild tensorboard directly so I don't see further action as essential.

**Comment by gar1t** [comment]
Still an issue in 0.7 :(

Will move to high priority to fix after 0.7 release.

Screeshot:

![Screenshot from 2020-05-21 19-33-04.png](https://images.zenhubusercontent.com/5b043dab4b5806bc2bd42a7a/1e152741-5242-45fe-bb5e-6f5f1462a72c)

**Comment by gar1t** [comment]
I'm not seeing this anymore in 0.7.2. I'm going close. We can reopen if I've missed something.

To create I ran the `recreate` script in https://github.com/guildai/issue-resolution/tree/master/32-duplicated-tensorboard-output.
